<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="85" started-at="2020-02-19T06:22:42Z" finished-at="2020-02-19T06:22:42Z">
    <groups>
      <group name="smoke">
        <method signature="Tc1_Login.secondclass()[pri:1, instance:com.automation.testcases.Tc1_Login@7d9d1a19]" name="secondclass" class="com.automation.testcases.Tc1_Login"/>
        <method signature="Tc1_Login.thirdclass()[pri:0, instance:com.automation.testcases.Tc1_Login@7d9d1a19]" name="thirdclass" class="com.automation.testcases.Tc1_Login"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Test" duration-ms="85" started-at="2020-02-19T06:22:42Z" finished-at="2020-02-19T06:22:42Z">
      <class name="com.automation.testcases.Tc1_Login">
        <test-method status="PASS" signature="thirdclass()[pri:0, instance:com.automation.testcases.Tc1_Login@7d9d1a19]" name="thirdclass" duration-ms="20" started-at="2020-02-19T06:22:42Z" description="My Sample Test Pass" finished-at="2020-02-19T06:22:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdclass -->
        <test-method status="FAIL" signature="secondclass()[pri:1, instance:com.automation.testcases.Tc1_Login@7d9d1a19]" name="secondclass" duration-ms="11" started-at="2020-02-19T06:22:42Z" description="My Sample Test Fail" finished-at="2020-02-19T06:22:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.automation.testcases.Tc1_Login.secondclass(Tc1_Login.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondclass -->
      </class> <!-- com.automation.testcases.Tc1_Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
